Hostname = '127.0.0.1'
Port = 48071
DBType = 'couchdb'
DBURL = '0.0.0.0'
DBUsername = 'testuser1'
DBPassword = 'password'
DBDatabase = 'coredata'
DBPort = 5984
DBConnectTimeout = 5000
DBSocketTimeout = 5000
ConsulHost = 'localhost'
ConsulPort = 8500
CheckInterval = '10s'
ConsulProfilesActive = 'go'
DistroHost = 'localhost'
DistroPort = 48070
